import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import DenseAppBar from './components/navbar'
import NextJsCarousel from './components/carousel'
import ResponsiveAppBar from './components/navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <ResponsiveAppBar/>
        <NextJsCarousel/>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
